In [2]:
import pandas as pd
import glob

files = glob.glob("pitch_logs/**/*.csv", recursive=True)
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

/var/folders/lr/9t8mdvqx6_58bf8fjvwdbh3h0000gp/T/ipykernel_1535/616367746.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

In [3]:
del df["Unnamed: 0"]

In [4]:
len(df)

7057848

In [5]:
df.to_csv("full_data.csv")

In [6]:
x = pd.read_csv("full_data.csv")
len(x)

7057848

In [6]:
pd.set_option('display.max_columns', None)
x

,Unnamed: 0,year,pitchingTeamId,pitchingTeam,conference,hittingTeamId,hittingTeam,gameId,gameDate,inning,balls,strikes,outs,pitcherId,Pitcher,pitcherHand,pitchType,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,pitchResult,atbatResult,relX,relZ,releaseVelocity,spinRate,spinDir,rv
0,0,2026,730238720,UNCG,D1 Southern Conference,730187776,CAMP,425360286,2026-04-07 18:05:00,1,0,0,1,1097769472,J. Horton,R,CH,0.52861,0.20209,-9.103058,11.53099,9.64678,-0.403931,5.71451,B,IP_OUT,-0.65433,5.72931,80.42213,1229.525980,224.543498,0.13
1,1,2026,730238720,UNCG,D1 Southern Conference,730187776,CAMP,425360286,2026-04-07 18:05:00,1,0,0,2,1097769472,J. Horton,R,FA,1.70463,2.63522,-5.591340,12.18717,6.41181,-1.573257,5.73828,B,K,-0.29520,5.73089,90.43824,2024.571468,210.594538,0.13
2,2,2026,730238720,UNCG,D1 Southern Conference,730187776,CAMP,425360286,2026-04-07 18:05:00,1,1,0,2,1097769472,J. Horton,R,FA,0.33847,3.38065,-4.947300,12.71363,8.12934,-0.043732,5.81721,B,K,-0.37963,5.67809,87.24150,2028.308428,215.817692,0.13
3,3,2026,730238720,UNCG,D1 Southern Conference,730187776,CAMP,425360286,2026-04-07 18:05:00,1,2,0,2,1097769472,J. Horton,R,SL,-1.74774,2.40177,-8.548971,-5.19351,-16.97926,-0.506099,5.03744,B,K,-0.80716,5.57632,77.06986,2133.077808,67.000448,0.13
4,4,2026,730238720,UNCG,D1 Southern Conference,730187776,CAMP,425360286,2026-04-07 18:05:00,1,3,0,2,1097769472,J. Horton,R,FA,0.48481,2.23758,-6.053796,13.27359,6.84737,-0.496317,5.79503,SL,K,-0.54790,5.63265,86.95662,1954.594273,209.941341,-0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6317027,6317027,2026,3030,HOU,D1 Big 12 Conference,730373376,WAKE,419127210,2026-02-13 20:06:00,9,1,1,2,1162034944,C. Scinta,L,CU,0.47046,2.80175,-7.926706,-7.21394,10.42532,1.746735,5.28038,SL,S,1.24060,5.34914,76.49930,2583.804262,310.001313,-0.15
6317028,6317028,2026,3030,HOU,D1 Big 12 Conference,730373376,WAKE,419127210,2026-02-13 20:06:00,9,1,2,2,1162034944,C. Scinta,L,FA,-0.60093,2.48937,-5.199526,15.34233,-8.89540,1.195930,6.20760,IP,S,1.24393,5.49582,89.34350,2350.723169,147.893876,1.00
6317029,6317029,2026,3030,HOU,D1 Big 12 Conference,730373376,WAKE,419127210,2026-02-13 20:06:00,9,0,0,2,1162034944,C. Scinta,L,FA,-0.35348,2.18100,-5.562575,16.18863,-10.94071,0.856227,5.79671,SL,K,1.35428,5.60261,89.06268,2322.748092,144.033594,-0.15
6317030,6317030,2026,3030,HOU,D1 Big 12 Conference,730373376,WAKE,419127210,2026-02-13 20:06:00,9,0,1,2,1162034944,C. Scinta,L,FA,-0.04849,3.35674,-4.468160,13.75784,-11.87879,0.392937,5.95429,SS,K,1.30506,5.56334,89.01777,2478.148156,136.888375,-0.15
6317031,6317031,2026,3030,HOU,D1 Big 12 Conference,730373376,WAKE,419127210,2026-02-13 20:06:00,9,0,2,2,1162034944,C. Scinta,L,FA,0.84522,3.54062,-4.216929,14.22489,-9.61308,-0.303701,5.71184,SS,K,1.36319,5.60829,89.69546,2460.408959,143.955555,-0.15

In [7]:
x.sort_values("releaseVelocity", ascending=False).head(25)

,Unnamed: 0,year,pitchingTeamId,pitchingTeam,conference,hittingTeamId,hittingTeam,gameId,gameDate,inning,balls,strikes,outs,pitcherId,Pitcher,pitcherHand,pitchType,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,pitchResult,atbatResult,relX,relZ,releaseVelocity,spinRate,spinDir,rv
1359809,1359809,2026,4807,ORE,D1 Big Ten Conference,5046,VAN,348793514,2026-03-01 14:00:00,1,0,0,2,1342168677,C. Scolari,R,SI,-1.397415,3.562569,-5.306908,20.171825,14.896358,2.618419,7.214916,F,K,-1.30384,5.677867,106.009424,2445.967218,216.444885,-0.15
1836605,1836605,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,0,0,0,1708220417,B. Joyce,R,SI,1.938250,0.638780,-6.467439,5.567010,19.752450,-2.762758,6.711210,B,IP_OUT,-2.23109,4.794180,104.311190,2537.049927,256.678640,0.13
1836606,1836606,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,1,0,0,1708220417,B. Joyce,R,SI,-0.358650,1.275640,-5.230696,11.734020,18.340800,-0.493652,6.546960,SL,IP_OUT,-2.33746,4.862790,104.230550,2505.033895,239.078604,-0.15
1836608,1836608,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,0,0,1,1708220417,B. Joyce,R,SI,0.340790,0.742060,-5.823519,12.014610,16.015560,-1.419190,6.553840,B,HR,-2.29316,4.860040,104.012490,2430.245573,235.065139,0.13
1808108,1808108,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,3,0,2,1708220417,B. Joyce,R,FA,1.049300,2.023620,-4.360893,14.258590,15.014420,-2.371162,6.500890,SL,K,-2.37584,4.968810,103.576060,2645.934939,228.145180,-0.15
1836603,1836603,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,3,2,0,1708220417,B. Joyce,R,SI,-0.684520,3.271660,-3.022401,13.243870,16.695840,-0.162513,6.795330,F,BB,-2.22188,4.877930,103.399820,2567.106668,233.420402,0.00
1836607,1836607,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,1,1,0,1708220417,B. Joyce,R,SI,0.822770,1.631090,-4.899607,11.045560,18.304770,-1.921139,6.785110,B,IP_OUT,-2.45263,4.795370,103.383020,2457.051244,240.781684,0.13
1808124,1808124,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,4,3,2,1,1708220417,B. Joyce,R,FA,-0.010610,1.259870,-5.486631,11.891940,16.383390,-1.014784,6.579750,IP,S,-2.30401,5.053070,103.354610,2469.416684,235.841520,1.00
1808109,1808109,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,3,1,2,1708220417,B. Joyce,R,FA,0.269180,1.802950,-4.496469,14.520600,14.091780,-1.563242,6.520790,F,K,-2.33731,4.887140,103.294300,2616.234388,225.773478,-0.15
1836604,1836604,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,3,2,0,1708220417,B. Joyce,R,FA,1.734660,0.881970,-5.736463,12.862250,14.450990,-2.737656,6.536430,B,BB,-1.97964,4.956160,103.283000,2491.728691,230.260948,0.80
1808121,1808121,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,4,1,1,1,1708220417,B. Joyce,R,FA,-0.160860,2.500560,-3.653651,16.198430,12.194260,-1.406560,6.371200,SS,S,-2.46964,4.956230,103.269330,2468.616184,218.334503,-0.15
1848325,1848325,2022,730153728,TENN,D1 Southeastern Conference,5362,UK,173106170,2022-05-05 13:00:00,10,1,2,2,1708220417,B. Joyce,R,FA,1.235460,1.467340,-4.776149,17.719220,16.867490,-2.255401,6.374610,B,IP_OUT,-2.24106,5.033420,103.103940,2534.772918,225.070390,0.13
1836601,1836601,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,2,1,0,1708220417,B. Joyce,R,FA,0.828720,2.289080,-3.842411,15.966030,15.148510,-1.826081,6.524980,SL,BB,-2.10608,4.852820,103.044120,2562.118802,225.099591,-0.15
1808099,1808099,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,2,2,1,1708220417,B. Joyce,R,FA,0.322010,2.867420,-3.413640,13.402210,14.157370,-1.775529,6.349290,F,IP_OUT,-2.48985,4.843620,102.922510,2481.707141,228.324287,0.00
1808100,1808100,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,0,0,2,1708220417,B. Joyce,R,FA,-1.478600,3.399200,-3.117731,14.833240,16.981980,0.511698,6.262410,B,HBP,-2.42044,5.184850,102.906670,2600.141992,230.601750,0.13
1808103,1808103,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,2,1,2,1708220417,B. Joyce,R,FA,-0.205930,0.546410,-5.999777,13.937250,16.010360,-0.969145,6.499200,B,HBP,-2.42769,4.951820,102.884430,2530.337589,230.671431,0.13
1808107,1808107,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,2,0,2,1708220417,B. Joyce,R,FA,1.350600,1.263280,-5.293633,12.992450,18.106580,-2.384266,6.657830,B,K,-2.33623,4.918380,102.844400,2490.874333,236.150465,0.13
1808122,1808122,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,4,1,2,1,1708220417,B. Joyce,R,FA,-1.270000,0.933450,-5.927707,10.203230,18.547450,0.387189,6.241260,B,S,-2.45837,4.973450,102.806560,2459.217965,243.113186,0.13
1808105,1808105,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,0,0,2,1708220417,B. Joyce,R,FA,1.761550,2.326500,-4.022911,14.277760,17.395400,-2.885267,6.464560,B,K,-2.33440,4.921100,102.783050,2605.478294,232.293387,0.13
1808120,1808120,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,4,0,1,1,1708220417,B. Joyce,R,FA,0.060930,0.541740,-5.843116,16.138240,12.910280,-1.548024,6.258510,B,S,-2.44071,5.010160,102.781650,2433.682186,220.030444,0.13
1808127,1808127,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,4,1,1,1,1708220417,B. Joyce,R,FA,-1.016550,3.148240,-3.100089,14.796230,14.157880,-0.282402,6.250450,B,HBP,-2.45525,4.928480,102.582090,2408.472868,225.370859,0.13
1808104,1808104,2022,730153728,TENN,D1 Southeastern Conference,5080,MSST,258788420,2022-05-21 13:00:00,3,3,1,2,1708220417,B. Joyce,R,FA,2.696940,2.088490,-4.452061,13.075910,14.949650,-4.163968,6.437330,HBP,HBP,-2.37696,4.978160,102.536530,2594.661786,230.636261,0.80
1205691,1205691,2022,730153728,TENN,D1 Southeastern Conference,730166272,TNTC,262983461,2022-04-12 13:00:00,6,0,0,2,1708220417,B. Joyce,R,FA,1.605390,1.242960,-5.262183,18.124540,18.488000,-2.439050,6.297660,B,K,-2.17729,5.232050,102.519820,2532.743859,227.178434,0.13
3888754,3888754,2024,5046,VAN,D1 Southeastern Conference,730200832,GONZ,4526486,2024-02-23 13:00:00,6,0,2,2,1297334784,G. Carter,R,FA,-0.403960,2.849420,-4.754977,12.246540,5.258550,-0.200492,6.791590,F,K,-1.02529,5.973880,102.516450,2114.987944,204.583515,0.00
1836600,1836600,2022,730153728,TENN,D1 Southeastern Conference,730168320,FLA,427041609,2022-05-29 13:00:00,8,1,1,0,1708220417,B. Joyce,R,FA,0.847350,1.044680,-5.167765,15.751900,15.055830,-1.957786,6.653570,B,BB,-2.19648,4.770230,102.472550,2493.438948,225.433350,0.13

In [21]:
x[(x["Pitcher"] == "K. Witherspoon") & (x["pitchType"] == "SL")].describe()

,Unnamed: 0,year,pitchingTeamId,hittingTeamId,gameId,inning,balls,strikes,outs,pitcherId,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,rv
count,5.740000e+02,574.000000,574.0,5.740000e+02,5.740000e+02,574.000000,574.000000,574.000000,574.000000,5.740000e+02,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000
mean,1.873234e+06,2024.374564,730294528.0,2.862482e+08,1.381421e+08,3.921603,0.796167,0.836237,1.024390,1.238202e+09,0.330620,2.065270,-7.130534,1.791340,-4.049052,-2.692594,5.480629,-1.850777,5.456080,83.795705,2334.077775,103.985406,0.063449
std,8.853605e+05,0.484432,0.0,3.568100e+08,1.859385e+08,2.174528,0.908705,0.810712,0.801023,0.000000e+00,0.871449,1.064593,1.756806,3.572909,2.797973,1.256651,0.278829,0.528683,1.011174,6.000415,290.660855,52.932799,0.332792
min,6.876640e+05,2024.000000,730294528.0,2.260000e+02,4.525829e+06,1.000000,0.000000,0.000000,0.000000,1.238202e+09,-2.281030,-1.125520,-11.195630,-8.634850,-13.584060,-5.785482,4.498590,-2.700780,1.600010,52.637900,803.354682,1.515527,-0.210000
25%,1.206386e+06,2024.000000,730294528.0,4.806000e+03,4.537335e+06,2.000000,0.000000,0.000000,0.000000,1.238202e+09,-0.267020,1.359520,-8.169916,-0.552288,-5.501245,-3.493367,5.303725,-2.206163,5.586475,83.876265,2328.976978,69.913855,-0.150000
50%,1.979414e+06,2024.000000,730294528.0,5.363000e+03,5.334848e+06,4.000000,1.000000,1.000000,1.000000,1.238202e+09,0.385230,2.033100,-7.390546,1.629665,-4.011680,-2.855314,5.470555,-1.896795,5.716785,84.995585,2399.371183,96.935096,0.000000
75%,2.011838e+06,2025.000000,730294528.0,7.301801e+08,3.493127e+08,5.000000,1.000000,2.000000,2.000000,1.238202e+09,0.909528,2.767807,-6.466274,3.708893,-2.582090,-2.061084,5.653555,-1.650785,5.822195,85.998515,2454.016800,127.087219,0.130000
max,5.132615e+06,2025.000000,730294528.0,7.303800e+08,4.988330e+08,9.000000,3.000000,2.000000,2.000000,1.238202e+09,2.918580,5.058450,0.890236,15.987410,10.345120,3.298753,6.561490,0.773790,6.161090,90.939490,3253.135250,359.828381,1.760000

In [22]:
x[(x["Pitcher"] == "C. Flukey") & (x["pitchType"] == "FA")].describe()

,Unnamed: 0,year,pitchingTeamId,hittingTeamId,gameId,inning,balls,strikes,outs,pitcherId,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,rv
count,1.268000e+03,1268.000000,1268.0,1.268000e+03,1.268000e+03,1268.000000,1268.000000,1268.000000,1268.000000,1.268000e+03,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000,1268.000000
mean,2.852655e+06,2024.642744,4104.0,4.970405e+08,1.664709e+08,3.741325,0.915615,0.875394,0.917192,1.238148e+09,0.199479,2.666145,-4.797272,20.461790,9.303488,-0.367916,6.562264,-0.912027,6.068963,94.773648,2256.428612,205.542834,0.061680
std,1.011352e+06,0.479380,0.0,3.406291e+08,1.407868e+08,2.265899,1.008242,0.839209,0.823062,0.000000e+00,0.771908,0.834809,0.937368,2.178636,2.673661,0.909606,0.257291,0.220340,0.122803,1.501656,103.637470,7.633865,0.359448
min,5.918000e+03,2024.000000,4104.0,2.320000e+02,4.492095e+06,1.000000,0.000000,0.000000,0.000000,1.238148e+09,-2.434720,0.151880,-8.136015,3.284770,-1.968660,-3.290513,5.745120,-1.571530,5.712190,84.559360,1686.113867,154.071528,-0.210000
25%,2.884539e+06,2024.000000,4104.0,5.420000e+03,4.538706e+06,2.000000,0.000000,0.000000,0.000000,1.238148e+09,-0.320130,2.096780,-5.411831,19.182158,7.593303,-0.992281,6.382830,-1.062020,5.971158,93.832510,2203.175266,200.842467,-0.150000
50%,2.917588e+06,2025.000000,4104.0,7.302403e+08,1.800373e+08,3.000000,1.000000,1.000000,1.000000,1.238148e+09,0.225935,2.670620,-4.782695,20.612945,9.360105,-0.360135,6.562210,-0.906495,6.072100,94.878145,2267.840687,205.631010,-0.150000
75%,3.078651e+06,2025.000000,4104.0,7.303337e+08,2.545631e+08,6.000000,2.000000,2.000000,2.000000,1.238148e+09,0.740410,3.235048,-4.184408,21.891452,10.961360,0.230706,6.734108,-0.762065,6.165560,95.815950,2326.224408,210.276991,0.130000
max,5.052061e+06,2025.000000,4104.0,7.303805e+08,4.896950e+08,9.000000,3.000000,2.000000,2.000000,1.238148e+09,2.522510,5.495550,-1.621120,26.573200,21.607890,2.613962,7.511790,-0.187880,6.422540,98.280090,2481.853871,240.059097,1.760000

In [23]:
x[(x["Pitcher"] == "A. Eyanson") & (x["pitchType"] == "SL") & (x["year"] == 2025)].describe()

,Unnamed: 0,year,pitchingTeamId,hittingTeamId,gameId,inning,balls,strikes,outs,pitcherId,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,rv
count,3.880000e+02,388.0,388.0,3.880000e+02,3.880000e+02,388.000000,388.000000,388.000000,388.000000,3.880000e+02,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000,388.000000
mean,1.729955e+06,2025.0,5323.0,2.503189e+08,3.076426e+08,3.484536,0.989691,0.984536,0.912371,1.152946e+09,0.104490,1.777793,-7.961286,0.897112,-2.527823,-1.800779,5.958374,-1.336280,5.745700,81.087421,2018.538152,110.178414,0.047603
std,1.025350e+06,0.0,0.0,3.470498e+08,1.226965e+08,2.071654,1.001238,0.859522,0.775964,0.000000e+00,0.789774,1.040564,2.476855,4.722392,3.033056,1.307867,0.605367,0.652287,1.705289,7.618536,339.267745,80.296028,0.341138
min,9.037740e+05,2025.0,5323.0,2.450000e+02,1.191682e+08,1.000000,0.000000,0.000000,0.000000,1.152946e+09,-3.047710,-1.003790,-12.484712,-14.983350,-14.647250,-4.984619,3.048600,-2.247200,0.917590,52.540000,872.905169,0.724195,-0.210000
25%,1.180664e+06,2025.0,5323.0,3.375000e+03,2.156200e+08,2.000000,0.000000,0.000000,0.000000,1.152946e+09,-0.366085,1.002890,-9.532747,-1.901743,-4.048353,-2.750408,5.881625,-1.904970,6.137833,82.404180,1994.265179,52.823405,-0.150000
50%,1.240732e+06,2025.0,5323.0,5.048000e+03,3.117797e+08,3.000000,1.000000,1.000000,1.000000,1.152946e+09,0.111480,1.723310,-8.593003,0.987935,-2.430080,-1.956305,6.106190,-1.676955,6.382205,83.812795,2089.200971,95.972944,-0.150000
75%,1.900238e+06,2025.0,5323.0,7.302070e+08,4.258634e+08,5.000000,2.000000,2.000000,2.000000,1.152946e+09,0.636250,2.478668,-7.354695,3.105720,-1.029072,-0.997655,6.286620,-0.721163,6.639527,84.999408,2185.122336,147.136115,0.130000
max,4.318294e+06,2025.0,5323.0,7.303485e+08,4.775314e+08,9.000000,3.000000,2.000000,2.000000,1.152946e+09,2.313510,4.512500,0.869002,14.382610,7.111660,2.989316,6.775090,0.838510,6.925330,88.712850,3228.024765,359.636918,1.760000

In [8]:
x[x["pitchType"] == "FA"].sort_values("spinRate", ascending=False).head(10)

,Unnamed: 0,year,pitchingTeamId,pitchingTeam,conference,hittingTeamId,hittingTeam,gameId,gameDate,inning,balls,strikes,outs,pitcherId,Pitcher,pitcherHand,pitchType,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,pitchResult,atbatResult,relX,relZ,releaseVelocity,spinRate,spinDir,rv
5544702,5544702,2024,730257152,BYU,D1 Big 12 Conference,730153984,UCD,4526976,2024-02-24 13:00:00,4,0,0,1,1088991744,C. Dahle,R,FA,0.932415,-1.317572,-12.643539,-22.726353,-21.904744,-5.374775,5.346191,IP,S,-2.078378,5.404199,91.054232,9653.117832,43.837877,1.00
5542170,5542170,2024,730224128,LBSU,D1 Big West Conference,730153984,UCD,4541017,2024-05-03 13:00:00,9,0,1,1,1282703872,M. Villani,R,FA,2.499463,0.579115,-8.836074,-20.398181,-14.700470,-5.911054,6.378930,B,BB,-1.398820,6.064663,94.837984,3655.061598,32.605429,0.13
5316810,5316810,2021,5326,PSU,D1 Big Ten Conference,730172928,MD,214375631,2021-03-21 13:00:00,9,0,1,2,1860002266,T. Shingledecker,L,FA,1.391453,2.342181,-5.849213,11.779115,-14.645722,0.207951,5.919044,SS,K,2.922668,5.558951,87.723306,3627.345634,128.889390,-0.15
5074830,5074830,2019,1551,MSU,D1 Big Ten Conference,2290,MICH,252768546,2019-03-30 13:00:00,7,0,2,0,1481168284,S. Benschoter,R,FA,0.794289,-1.647505,-10.363486,9.742120,15.951313,-0.336740,6.263283,B,FC,-0.980036,5.533045,87.035852,3565.160599,238.495558,0.13
2429913,2429913,2024,5342,CMU,D1 Mid-American Conference,730256640,UCF,4538083,2024-04-19 13:00:00,8,0,0,2,1136407552,B. Vitas,R,FA,-0.267950,1.227940,-6.707798,13.380600,15.365360,0.108609,4.327920,SL,IP_OUT,-1.445510,5.267000,87.161910,3564.221153,232.091059,-0.15
2813656,2813656,2025,730230272,NKU,D1 Horizon League,730284544,YSU,268962968,2025-04-11 18:02:00,9,3,1,1,1266273549,E. Fry,R,FA,1.263570,1.728280,-9.577666,-7.135830,-9.700360,-3.566007,5.046670,B,BB,-1.289550,6.272860,80.308510,3551.840736,48.607116,0.80
5891946,5891946,2021,730181888,UNC,D1 Atlantic Coast Conference,101,FSU,380646315,2021-04-04 13:00:00,7,2,1,0,1225193319,C. Joyner,L,FA,0.077378,0.863867,-6.805282,13.707877,-16.763250,-0.294177,6.002173,SS,K,1.337272,4.985395,85.613862,3518.409651,129.346973,-0.15
4450965,4450965,2026,730153728,TENN,D1 Southeastern Conference,730167552,BU,148029664,2026-02-24 16:02:00,2,0,0,0,1722877754,C. Appenzeller,L,FA,0.253160,3.126220,-4.819835,12.602210,-15.780640,0.709889,6.846890,SS,BB,2.213700,5.629700,90.284930,3507.652517,126.051264,-0.15
3368763,3368763,2021,730378496,TROY,D1 Sun Belt Conference,5324,UTA,338626109,2021-05-28 13:00:00,5,0,1,0,1323248384,R. Pettys,L,FA,1.196470,1.842290,-6.191653,12.694420,-2.940990,0.031621,5.644440,SS,K,1.471360,5.785000,91.989660,3499.732691,165.904910,-0.15
528066,528066,2022,245,TEX,D1 Big 12 Conference,730205440,AFA,300496127,2022-04-20 13:00:00,6,3,1,1,1759220635,C. Cobb,R,FA,0.203320,2.646150,-5.401989,7.775240,17.796700,-2.518349,4.786420,F,IP_OUT,-3.663660,5.072880,87.293510,3494.710937,249.566060,-0.15

In [25]:
x.describe()

,Unnamed: 0,year,pitchingTeamId,hittingTeamId,gameId,inning,balls,strikes,outs,pitcherId,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,rv
count,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06,5.256644e+06
mean,2.628322e+06,2.023364e+03,4.499694e+08,4.432143e+08,2.289479e+08,4.872205e+00,8.976351e-01,8.218689e-01,9.853800e-01,1.316772e+09,6.935767e-02,2.280625e+00,-6.602402e+00,9.026888e+00,2.111180e+00,-6.967541e-01,5.794325e+00,-7.553071e-01,5.708728e+00,8.521379e+01,2.176194e+03,1.788274e+02,9.548101e-02
std,1.517463e+06,1.590511e+00,3.548223e+08,3.564267e+08,1.620671e+08,2.563687e+00,9.810954e-01,8.171457e-01,8.160032e-01,2.292173e+08,1.011714e+00,1.053787e+00,1.871824e+00,9.336217e+00,1.177946e+01,2.138813e+00,5.924931e-01,1.773103e+00,5.636718e-01,5.947239e+00,3.044282e+02,7.243414e+01,3.572039e-01
min,0.000000e+00,2.019000e+03,1.000000e+02,1.000000e+02,4.491801e+06,1.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,1.000036e+09,-1.769456e+01,-8.889640e+00,-2.552899e+01,-5.515771e+01,-5.782787e+01,-1.145509e+01,-3.443120e+00,-8.344250e+00,-1.182120e-01,4.436093e+01,1.289039e+02,7.967555e-05,-2.100000e-01
25%,1.314161e+06,2.022000e+03,5.080000e+03,5.080000e+03,1.028189e+08,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.162441e+09,-6.117600e-01,1.581480e+00,-7.835473e+00,2.435562e+00,-8.134860e+00,-2.091981e+00,5.398870e+00,-1.982590e+00,5.417720e+00,8.062315e+01,2.026788e+03,1.267434e+02,-1.500000e-01
50%,2.628322e+06,2.024000e+03,7.301903e+08,7.301842e+08,2.378998e+08,5.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.253487e+09,7.440000e-02,2.276011e+00,-6.399150e+00,1.062068e+01,3.939810e+00,-7.077310e-01,5.795620e+00,-1.362000e+00,5.753130e+00,8.621179e+01,2.199364e+03,1.984870e+02,0.000000e+00
75%,3.942482e+06,2.025000e+03,7.302851e+08,7.302845e+08,3.697461e+08,7.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,1.341980e+09,7.528300e-01,2.979310e+00,-5.238929e+00,1.661739e+01,1.228953e+01,6.264838e-01,6.190090e+00,8.090600e-01,6.066180e+00,8.996764e+01,2.357880e+03,2.291642e+02,1.300000e-01
max,5.256643e+06,2.025000e+03,8.021069e+08,7.543153e+08,4.999794e+08,1.900000e+01,6.000000e+00,5.000000e+00,2.000000e+00,1.999822e+09,1.322449e+01,2.323087e+01,9.660112e+00,6.174393e+01,5.417999e+01,1.397855e+01,1.363697e+01,9.025478e+00,9.639279e+00,1.043112e+02,9.653118e+03,3.599997e+02,1.760000e+00