In [2]:
import pandas as pd
import numpy as np
import pickle
from lightgbm import LGBMRegressor
MODELS_CACHE = {}

In [3]:
df = pd.read_csv("full_data.csv")

In [4]:
pitchers = list(df["pitcherId"].unique())
pitches = list(df["pitchType"].unique())
pitches.remove("KN")
pitches.remove("ST")
lr = ["L", "R"]

features = ['inducedVertBreak', 'horzBreak', 'extension', 'relX', 'relZ', 'releaseVelocity', 'spinRate']
targets = ["rv"]

test = df[df["year"] == 2026]

In [5]:
def pred_rv(test, features, target, pitch, side):
    if (pitch, side) not in MODELS_CACHE:
        with open(f'models/26_{pitch}_{side}.pkl', 'rb') as f:
            MODELS_CACHE[(pitch, side)] = pickle.load(f)

    model = MODELS_CACHE[(pitch, side)]
    X_test = test[features]
    predictions = model.predict(X_test) 
    
    return pd.Series(predictions, index=test.index)

In [6]:
dfs = []

for pitcher in pitchers: 
    for pitch in pitches: 
        for side in lr: 
            te = test[(test["pitcherId"] == pitcher) & (test["pitchType"] == pitch) & (test["pitcherHand"] == side)] 
            if len(te) >= 10: 
                dfx = {} 
                dfx["Pitcher"] = te["Pitcher"].iloc[0]
                dfx["pitcherId"] = pitcher
                dfx["Team"] = te["pitchingTeam"].iloc[0]
                dfx["PitchType"] = pitch 
                dfx["PitcherThrows"] = side 
                dfx["Count"] = len(te) 
                for feature in features: 
                    dfx[feature] = te[feature].mean() 
                for target in targets: 
                    dfz = pd.DataFrame([dfx], columns=features) 
                    dfx["xrv"] = float(pred_rv(dfz, features, target, pitch, side).iloc[0]) 
                dfs.append(dfx)

In [7]:
stuff = pd.DataFrame(dfs).reset_index(drop=True)

In [8]:
stuff[stuff["Team"] == "URI"].sort_values("xrv")

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,inducedVertBreak,horzBreak,extension,relX,relZ,releaseVelocity,spinRate,xrv
2836,E. Maloney,1085415168,URI,CH,R,29,9.200727,11.137915,4.980640,-0.189884,6.829958,76.225244,1451.312982,0.020714
2846,J. Kopetski,1269533184,URI,FC,L,19,6.771141,4.331412,6.235199,2.088972,5.640634,75.404928,1738.530242,0.045295
3409,J. Sabbath,1110853376,URI,SL,R,160,5.175643,-11.907250,5.781683,-1.805022,5.680606,78.781352,2350.915489,0.050557
10377,L. Lavigueur,1143021056,URI,SL,R,76,-5.820478,-20.799608,5.245887,-1.487878,5.928555,78.427225,2515.432751,0.055412
3392,J. Cullen,1358089441,URI,FA,R,203,22.665115,10.827551,5.994514,-1.004210,6.129405,91.638213,2253.720642,0.055759
3390,D. Asencio,1241946368,URI,SL,R,12,6.660355,-11.770542,5.675755,-1.935682,5.841291,75.512682,2326.185922,0.060447
3986,C. Grotyohann,1203468032,URI,FA,R,38,22.637336,8.417300,5.913379,-1.917919,6.220504,90.554157,2188.620738,0.063762
3393,J. Cullen,1358089441,URI,SL,R,57,4.681646,-4.079590,5.550405,-1.438953,5.851182,83.456744,2520.911163,0.065969
3406,A. Jones,1101042688,URI,FC,R,14,5.622384,-0.570624,5.430084,-1.466703,5.832419,82.295189,2278.644448,0.067727
2839,C. Maloney,1336247552,URI,CH,R,11,11.786229,11.637562,5.035975,-0.659251,6.603807,77.606979,1253.749276,0.068884
3394,J. Cullen,1358089441,URI,CU,R,32,-13.104168,-13.957630,5.217344,-1.098272,6.237111,75.556880,2699.948849,0.070362
2841,C. Maloney,1336247552,URI,SL,R,47,-3.544865,-7.224586,5.338498,-2.278793,5.773711,81.802477,2551.530194,0.071778
2847,C. Johnston,1241946624,URI,CH,R,83,10.891403,13.513926,6.435540,-0.684517,6.099914,79.698941,1724.467899,0.072624
3401,M. Santos,1487988943,URI,SL,R,81,1.337573,-15.439549,5.196143,-2.640169,5.009101,82.496835,2664.887714,0.075147
3404,A. Jones,1101042688,URI,SL,R,20,1.145936,-4.533494,5.362061,-1.270768,5.880472,81.781744,2300.561485,0.075819
12251,T. Turner,1310825728,URI,SL,R,52,-2.334176,-8.995563,5.088074,-1.565798,5.467264,80.198749,2465.900924,0.076006
2849,C. Johnston,1241946624,URI,SL,R,47,6.107274,-5.173034,6.147280,-0.745119,6.114137,79.431728,2307.258337,0.076565
3395,J. Cullen,1358089441,URI,FC,R,50,4.408772,-3.518393,5.540961,-1.554140,5.877405,83.127495,2531.746514,0.077020
3410,J. Sabbath,1110853376,URI,CU,R,52,-2.403696,-13.155317,5.753100,-1.513430,5.854035,76.146877,2366.135918,0.078264
2842,C. Maloney,1336247552,URI,CU,R,14,-6.502419,-5.048855,4.985724,-1.318161,6.303588,77.820639,2260.802113,0.078380
15542,W. Creed,1299086745,URI,FA,L,28,21.377306,-14.409316,5.577961,0.522100,6.484818,86.696848,2159.352794,0.086662
12252,S. Houchens,1194448803,URI,CH,L,17,3.608670,-12.115286,5.769125,2.144846,5.656192,80.607788,2003.201496,0.087150
2838,E. Maloney,1085415168,URI,CU,R,18,-7.729947,0.593396,4.668376,-0.320312,6.791754,73.765411,1878.843684,0.087365
3407,J. Sabbath,1110853376,URI,CH,R,31,4.573101,11.150609,6.723756,-1.973337,5.558579,84.829852,1644.158559,0.088163
3399,P. Aikens,1299756340,URI,SI,L,18,4.764121,-20.399713,4.327644,2.940219,5.045278,84.166399,2121.396425,0.089687
3405,A. Jones,1101042688,URI,CU,R,17,-14.775624,-9.868420,5.412468,-1.232744,5.882110,76.394230,2541.909695,0.090011
3400,M. Santos,1487988943,URI,FA,R,108,16.154692,8.102906,5.610465,-2.416509,5.292402,92.753839,2450.193301,0.091720
2843,J. Kopetski,1269533184,URI,CH,L,38,12.620039,-12.425595,6.507414,2.040878,5.533234,78.207835,1664.061929,0.091912
3403,A. Jones,1101042688,URI,FA,R,70,20.956155,8.634500,5.932586,-1.227173,5.846486,89.160199,2129.800095,0.092568
3398,P. Aikens,1299756340,URI,SL,L,99,4.944157,17.102180,4.262120,2.937638,4.640972,72.363382,2646.936419,0.095017
2845,J. Kopetski,1269533184,URI,SL,L,29,6.653576,-0.726200,6.322359,2.294893,5.599082,75.975696,1652.370530,0.095475
3408,J. Sabbath,1110853376,URI,FA,R,277,18.532330,2.662987,6.476050,-1.583716,5.794470,89.993407,2226.985430,0.095636
3987,C. Grotyohann,1203468032,URI,FC,R,19,6.040737,-2.849005,6.102057,-1.961467,6.158707,83.761543,2034.453420,0.097475
2840,C. Maloney,1336247552,URI,FA,R,74,19.661289,10.335407,5.860569,-1.789825,6.062133,89.648200,2180.454587,0.099052
3396,P. Aikens,1299756340,URI,CH,L,14,4.189062,-22.905299,4.761738,2.995582,4.900506,82.696306,2052.169521,0.100792
3391,J. Cullen,1358089441,URI,CH,R,50,11.246367,14.563543,5.917306,-1.269653,6.098354,85.259729,1580.037017,0.102767
3402,A. Jones,1101042688,URI,CH,R,10,9.996009,10.653069,5.561446,-1.486844,5.752253,82.041513,1437.920472,0.104230
12253,S. Houchens,1194448803,URI,FA,L,117,19.462327,-11.906755,5.454475,1.613177,6.242116,88.307414,2108.209682,0.105099
3397,P. Aikens,1299756340,URI,FA,L,108,6.232317,-20.778493,4.689027,2.908343,4.902015,82.422487,2069.716860,0.115986
12254,S. Houchens,1194448803,URI,SL,L,115,1.130586,2.491964,5.382143,2.230778,5.706410,79.667996,2289.964960,0.120072
3389,D. Asencio,1241946368,URI,FA,R,35,19.175383,16.102297,5.952148,-1.698610,5.998311,86.628407,2230.155496,0.124475
12249,T. Turner,1310825728,URI,CH,R,19,13.287937,14.223190,5.670312,-1.647894,5.344510,86.142376,1662.667146,0.125069
12250,T. Turner,1310825728,URI,FA,R,141,14.423120,12.753378,5.768207,-1.435739,5.489282,91.051711,2150.233992,0.127673
2844,J. Kopetski,1269533184,URI,FA,L,95,21.620212,-10.545366,6.408105,1.794032,5.847637,83.299141,1733.367662,0.132334
2837,E. Maloney,1085415168,URI,FA,R,81,20.822747,13.380084,5.315158,-0.191596,6.935071,87.312338,2123.062561,0.134308
10376,L. Lavigueur,1143021056,URI,FA,R,80,14.331502,9.084335,6.183493,-1.409080,6.028021,89.742849,2205.376487,0.137395
2850,C. Johnston,1241946624,URI,FC,R,20,12.078674,0.483619,6.404736,-0.644726,6.237177,82.213275,2228.981815,0.163343
2848,C. Johnston,1241946624,URI,FA,R,154,16.961047,9.146255,6.473720,-0.639851,6.096684,85.508398,2184.047341,0.170489

In [9]:
from scipy import stats

#df['zscore'] = stats.zscore(df['column'])
stuff["Stuff+"] = 100 + (-10 * stuff.groupby("PitchType")["xrv"].transform(stats.zscore))
stuff["Stuff+"] = stuff["Stuff+"].round().astype(int)

In [10]:
stuff.sort_values("Stuff+", ascending=False)

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,inducedVertBreak,horzBreak,extension,relX,relZ,releaseVelocity,spinRate,xrv,Stuff+
6175,C. Oliff,1579384799,ETSU,SL,R,54,11.776464,-5.543496,6.070116,-5.504503,3.394192,76.588125,2223.249877,-0.026250,158
4428,L. Earnhardt,1160764160,WIN,FS,L,66,1.416358,-6.970572,5.306394,1.314118,6.493396,78.006762,1104.887054,-0.404758,153
8788,I. Lohse,1102217728,MIZZ,FC,L,30,8.650791,0.240221,5.280999,1.145014,4.968095,87.251003,2562.277705,-0.115568,149
5469,D. Volantis,1979617275,TEX,SL,L,20,-0.147991,-1.393318,4.832832,2.250061,6.857666,87.127748,2568.711395,-0.005778,146
2210,O. Pudvar,1909941695,CONN,FC,L,46,10.731068,-0.038378,5.131493,0.902312,5.244803,84.537952,2155.593190,-0.100609,145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6717,R. Haider,1130936576,WSU,SL,R,15,3.280341,-8.424923,5.725601,-4.629531,3.492356,76.656960,2314.115270,0.173495,47
11215,J. Easterlin,1327301888,OAK,CU,R,12,1.393492,-2.239383,6.471502,-0.702690,6.456589,69.045468,1729.885104,0.211094,47
10877,C. Wade,1238048512,ALCN,FA,L,58,16.063925,-2.296364,5.617000,1.627021,5.399237,64.696430,1497.050535,0.245445,46
11604,S. Cooper,1578909932,ULM,SL,R,28,1.885338,-12.742766,5.087992,-1.748968,5.325088,69.337926,1927.949200,0.176279,45
16265,A. Morrison,1826790729,UOTS,SL,R,24,0.970376,0.560592,6.305503,-4.286565,3.027782,67.300445,1645.608299,0.183120,41

In [11]:
stuff.to_csv("stuff.csv")

In [12]:
stuff[stuff["Count"] > 200].sort_values("Stuff+", ascending=False)

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,inducedVertBreak,horzBreak,extension,relX,relZ,releaseVelocity,spinRate,xrv,Stuff+
6764,S. Matson,1198395392,USC,FA,L,244,16.797915,-16.320475,6.147980,1.708561,4.783717,90.319948,2314.911548,0.030045,136
7406,H. Dietz,1301090561,ARK,FA,L,277,17.110409,-6.439685,6.067808,2.037489,6.813163,95.028413,2394.163303,0.038339,132
2225,C. West,1310862081,CONN,FA,L,237,23.930800,-5.804477,6.038546,0.326793,6.154180,90.451656,2224.082182,0.040783,131
6784,J. Harper,1700152819,CSF,FA,L,297,18.059018,-16.164177,5.913329,1.642396,5.637875,90.162148,2239.679651,0.047020,129
6641,M. Brassfield,1038792681,TCU,SL,L,270,-0.331374,7.461935,5.443446,1.941769,6.261726,84.944340,2747.018745,0.025619,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5960,M. Eagen,1995173029,QUC,FA,R,236,14.921013,14.029757,6.089453,-1.136470,6.032340,89.128035,2376.843993,0.152633,85
14714,J. Price,1342170246,EKY,FA,R,309,12.780923,12.355080,5.938767,-1.473288,5.870021,86.937260,2320.744913,0.151117,85
14182,C. McMullen,1775801108,KENN,SI,R,213,9.898919,13.015634,5.948060,-1.197313,6.197967,92.420368,1961.651332,0.180219,81
3071,L. Jones,1997059014,CCAR,SI,R,233,8.919814,17.407073,5.573061,-1.604692,5.181255,88.874009,2364.260916,0.183724,79
10887,L. Knight,1328140800,CIN,FA,R,202,14.530766,2.819529,6.327396,-0.423823,6.614683,88.739556,2540.883292,0.174409,76

In [13]:
stuff[(stuff["Team"] == "URI") & (stuff["Count"] >= 11)].sort_values("Stuff+", ascending=False).head(60)

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,inducedVertBreak,horzBreak,extension,relX,relZ,releaseVelocity,spinRate,xrv,Stuff+
2836,E. Maloney,1085415168,URI,CH,R,29,9.200727,11.137915,4.980640,-0.189884,6.829958,76.225244,1451.312982,0.020714,133
3392,J. Cullen,1358089441,URI,FA,R,203,22.665115,10.827551,5.994514,-1.004210,6.129405,91.638213,2253.720642,0.055759,125
3986,C. Grotyohann,1203468032,URI,FA,R,38,22.637336,8.417300,5.913379,-1.917919,6.220504,90.554157,2188.620738,0.063762,122
3409,J. Sabbath,1110853376,URI,SL,R,160,5.175643,-11.907250,5.781683,-1.805022,5.680606,78.781352,2350.915489,0.050557,115
10377,L. Lavigueur,1143021056,URI,SL,R,76,-5.820478,-20.799608,5.245887,-1.487878,5.928555,78.427225,2515.432751,0.055412,112
15542,W. Creed,1299086745,URI,FA,L,28,21.377306,-14.409316,5.577961,0.522100,6.484818,86.696848,2159.352794,0.086662,112
2839,C. Maloney,1336247552,URI,CH,R,11,11.786229,11.637562,5.035975,-0.659251,6.603807,77.606979,1253.749276,0.068884,112
3400,M. Santos,1487988943,URI,FA,R,108,16.154692,8.102906,5.610465,-2.416509,5.292402,92.753839,2450.193301,0.091720,110
3403,A. Jones,1101042688,URI,FA,R,70,20.956155,8.634500,5.932586,-1.227173,5.846486,89.160199,2129.800095,0.092568,110
2847,C. Johnston,1241946624,URI,CH,R,83,10.891403,13.513926,6.435540,-0.684517,6.099914,79.698941,1724.467899,0.072624,110
2846,J. Kopetski,1269533184,URI,FC,L,19,6.771141,4.331412,6.235199,2.088972,5.640634,75.404928,1738.530242,0.045295,109
3390,D. Asencio,1241946368,URI,SL,R,12,6.660355,-11.770542,5.675755,-1.935682,5.841291,75.512682,2326.185922,0.060447,109
3399,P. Aikens,1299756340,URI,SI,L,18,4.764121,-20.399713,4.327644,2.940219,5.045278,84.166399,2121.396425,0.089687,108
3408,J. Sabbath,1110853376,URI,FA,R,277,18.532330,2.662987,6.476050,-1.583716,5.794470,89.993407,2226.985430,0.095636,108
2840,C. Maloney,1336247552,URI,FA,R,74,19.661289,10.335407,5.860569,-1.789825,6.062133,89.648200,2180.454587,0.099052,107
3393,J. Cullen,1358089441,URI,SL,R,57,4.681646,-4.079590,5.550405,-1.438953,5.851182,83.456744,2520.911163,0.065969,106
12253,S. Houchens,1194448803,URI,FA,L,117,19.462327,-11.906755,5.454475,1.613177,6.242116,88.307414,2108.209682,0.105099,105
12252,S. Houchens,1194448803,URI,CH,L,17,3.608670,-12.115286,5.769125,2.144846,5.656192,80.607788,2003.201496,0.087150,103
2841,C. Maloney,1336247552,URI,SL,R,47,-3.544865,-7.224586,5.338498,-2.278793,5.773711,81.802477,2551.530194,0.071778,103
3394,J. Cullen,1358089441,URI,CU,R,32,-13.104168,-13.957630,5.217344,-1.098272,6.237111,75.556880,2699.948849,0.070362,103
3407,J. Sabbath,1110853376,URI,CH,R,31,4.573101,11.150609,6.723756,-1.973337,5.558579,84.829852,1644.158559,0.088163,103
3406,A. Jones,1101042688,URI,FC,R,14,5.622384,-0.570624,5.430084,-1.466703,5.832419,82.295189,2278.644448,0.067727,103
12251,T. Turner,1310825728,URI,SL,R,52,-2.334176,-8.995563,5.088074,-1.565798,5.467264,80.198749,2465.900924,0.076006,101
3395,J. Cullen,1358089441,URI,FC,R,50,4.408772,-3.518393,5.540961,-1.554140,5.877405,83.127495,2531.746514,0.077020,101
3404,A. Jones,1101042688,URI,SL,R,20,1.145936,-4.533494,5.362061,-1.270768,5.880472,81.781744,2300.561485,0.075819,101
2843,J. Kopetski,1269533184,URI,CH,L,38,12.620039,-12.425595,6.507414,2.040878,5.533234,78.207835,1664.061929,0.091912,101
3401,M. Santos,1487988943,URI,SL,R,81,1.337573,-15.439549,5.196143,-2.640169,5.009101,82.496835,2664.887714,0.075147,101
3410,J. Sabbath,1110853376,URI,CU,R,52,-2.403696,-13.155317,5.753100,-1.513430,5.854035,76.146877,2366.135918,0.078264,100
2842,C. Maloney,1336247552,URI,CU,R,14,-6.502419,-5.048855,4.985724,-1.318161,6.303588,77.820639,2260.802113,0.078380,100
3397,P. Aikens,1299756340,URI,FA,L,108,6.232317,-20.778493,4.689027,2.908343,4.902015,82.422487,2069.716860,0.115986,100
2849,C. Johnston,1241946624,URI,SL,R,47,6.107274,-5.173034,6.147280,-0.745119,6.114137,79.431728,2307.258337,0.076565,100
3396,P. Aikens,1299756340,URI,CH,L,14,4.189062,-22.905299,4.761738,2.995582,4.900506,82.696306,2052.169521,0.100792,97
2838,E. Maloney,1085415168,URI,CU,R,18,-7.729947,0.593396,4.668376,-0.320312,6.791754,73.765411,1878.843684,0.087365,97
3391,J. Cullen,1358089441,URI,CH,R,50,11.246367,14.563543,5.917306,-1.269653,6.098354,85.259729,1580.037017,0.102767,96
3389,D. Asencio,1241946368,URI,FA,R,35,19.175383,16.102297,5.952148,-1.698610,5.998311,86.628407,2230.155496,0.124475,96
3987,C. Grotyohann,1203468032,URI,FC,R,19,6.040737,-2.849005,6.102057,-1.961467,6.158707,83.761543,2034.453420,0.097475,96
12250,T. Turner,1310825728,URI,FA,R,141,14.423120,12.753378,5.768207,-1.435739,5.489282,91.051711,2150.233992,0.127673,95
3405,A. Jones,1101042688,URI,CU,R,17,-14.775624,-9.868420,5.412468,-1.232744,5.882110,76.394230,2541.909695,0.090011,95
2844,J. Kopetski,1269533184,URI,FA,L,95,21.620212,-10.545366,6.408105,1.794032,5.847637,83.299141,1733.367662,0.132334,93
2837,E. Maloney,1085415168,URI,FA,R,81,20.822747,13.380084,5.315158,-0.191596,6.935071,87.312338,2123.062561,0.134308,92
10376,L. Lavigueur,1143021056,URI,FA,R,80,14.331502,9.084335,6.183493,-1.409080,6.028021,89.742849,2205.376487,0.137395,91
2845,J. Kopetski,1269533184,URI,SL,L,29,6.653576,-0.726200,6.322359,2.294893,5.599082,75.975696,1652.370530,0.095475,90
3398,P. Aikens,1299756340,URI,SL,L,99,4.944157,17.102180,4.262120,2.937638,4.640972,72.363382,2646.936419,0.095017,90
12249,T. Turner,1310825728,URI,CH,R,19,13.287937,14.223190,5.670312,-1.647894,5.344510,86.142376,1662.667146,0.125069,86
2850,C. Johnston,1241946624,URI,FC,R,20,12.078674,0.483619,6.404736,-0.644726,6.237177,82.213275,2228.981815,0.163343,80
2848,C. Johnston,1241946624,URI,FA,R,154,16.961047,9.146255,6.473720,-0.639851,6.096684,85.508398,2184.047341,0.170489,77
12254,S. Houchens,1194448803,URI,SL,L,115,1.130586,2.491964,5.382143,2.230778,5.706410,79.667996,2289.964960,0.120072,76

In [14]:
stuff[(stuff["Count"] > 50) & (stuff["PitchType"] == "FA")].sort_values("Stuff+", ascending=False).head(10)

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,inducedVertBreak,horzBreak,extension,relX,relZ,releaseVelocity,spinRate,xrv,Stuff+
441,J. Music,1161348114,CAMP,FA,R,112,21.717838,14.051507,5.627380,-3.628881,5.898753,91.553440,2226.384722,0.010936,144
6764,S. Matson,1198395392,USC,FA,L,244,16.797915,-16.320475,6.147980,1.708561,4.783717,90.319948,2314.911548,0.030045,136
9372,S. Garcia,1602557566,LSU,FA,L,118,21.774008,-10.973115,6.184411,1.553425,6.258128,92.701719,2461.242677,0.031237,135
7406,H. Dietz,1301090561,ARK,FA,L,277,17.110409,-6.439685,6.067808,2.037489,6.813163,95.028413,2394.163303,0.038339,132
13954,J. Nottingham,1557710177,UGA,FA,R,97,21.129491,11.899358,6.104974,-1.516178,6.158468,96.271623,2559.413119,0.038118,132
2225,C. West,1310862081,CONN,FA,L,237,23.930800,-5.804477,6.038546,0.326793,6.154180,90.451656,2224.082182,0.040783,131
5502,T. Burns,1207858176,TEX,FA,R,112,23.144534,4.586872,6.105255,-0.695601,6.561737,96.352919,2234.905418,0.042177,131
11644,C. Clark,1956935142,USM,FA,R,177,21.703584,9.329253,6.563693,-1.717891,5.478274,93.931105,2258.346428,0.042846,130
1860,D. Sheerin,1213263616,LSU,FA,R,172,14.680648,15.875060,6.066550,-3.455965,5.459771,96.465379,2442.404512,0.044374,130
5917,J. Soucie,1221790928,UK,FA,L,91,17.319146,-15.088271,5.826764,3.052747,6.390206,92.112573,2208.649834,0.043308,130

In [15]:
stuff[stuff["pitcherId"] == 1110853376]["Count"].sum()

np.int64(520)

In [16]:
import pandas as pd
import numpy as np
stuff = pd.read_csv("stuff.csv")
pitches = list(stuff["PitchType"].unique())

In [17]:
rows = []
ids = list(stuff["pitcherId"].unique())

for i in ids:
    x = stuff[stuff["pitcherId"] == i]
    dx = {}
    dx["Pitcher"] = x["Pitcher"].iloc[0]
    dx["pitcherId"] = i
    dx["Team"] = x["Team"].iloc[0]
    dx["PitcherThrows"] = x["PitcherThrows"].iloc[0]
    for pt in list(stuff["PitchType"].unique()):
        if pt in list(x["PitchType"].unique()):
            dx["Stf+ " + pt] = x[x["PitchType"] == pt]["Stuff+"].iloc[0].astype("int64")
            dx[pt + "_ct"] = x[x["PitchType"] == pt]["Count"].iloc[0]
        else:
            dx["Stf+ " + pt] = np.nan
    dx["Total"] = x["Count"].sum()
    rows.append(dx)

In [18]:
table = pd.DataFrame(rows).reset_index(drop=True)
stf_cols = [col for col in table.columns if col.startswith("Stf+")]
table[stf_cols] = table[stf_cols].astype("Int64")

table["Stuff+"] = 0.0
for p in pitches:
    col = "Stf+ " + p
    ct_col = p + "_ct"
    if col in table.columns and ct_col in table.columns:
        mask = table[col].notna()
        table.loc[mask, "Stuff+"] += (
            table.loc[mask, col] * (table.loc[mask, ct_col] / table.loc[mask, "Total"])
        )

table["Stuff+"] = table["Stuff+"].round().astype(int)
table = table[["Pitcher", "pitcherId", "Team", "Total", "PitcherThrows", "Stf+ FA", "Stf+ SL", "Stf+ CU", "Stf+ FC", "Stf+ SI", "Stf+ CH", "Stf+ FS", "Stuff+"]]

In [19]:
table[table["Team"] == "URI"].sort_values("Stuff+", ascending=False)

,Pitcher,pitcherId,Team,Total,PitcherThrows,Stf+ FA,Stf+ SL,Stf+ CU,Stf+ FC,Stf+ SI,Stf+ CH,Stf+ FS,Stuff+
969,J. Cullen,1358089441,URI,392,R,125,106,103,101,<NA>,96,<NA>,114
1143,C. Grotyohann,1203468032,URI,57,R,122,<NA>,<NA>,96,<NA>,<NA>,<NA>,113
4696,W. Creed,1299086745,URI,28,L,112,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,112
973,J. Sabbath,1110853376,URI,520,R,108,115,100,<NA>,<NA>,103,<NA>,109
971,M. Santos,1487988943,URI,189,R,110,101,<NA>,<NA>,<NA>,<NA>,<NA>,106
796,C. Maloney,1336247552,URI,146,R,107,103,100,<NA>,<NA>,112,<NA>,105
972,A. Jones,1101042688,URI,131,R,110,101,95,103,<NA>,96,<NA>,105
795,E. Maloney,1085415168,URI,128,R,92,<NA>,97,<NA>,<NA>,133,<NA>,102
2993,L. Lavigueur,1143021056,URI,156,R,91,112,<NA>,<NA>,<NA>,<NA>,<NA>,101
968,D. Asencio,1241946368,URI,47,R,96,109,<NA>,<NA>,<NA>,<NA>,<NA>,99
797,J. Kopetski,1269533184,URI,181,L,93,90,<NA>,109,<NA>,101,<NA>,96
970,P. Aikens,1299756340,URI,239,L,100,90,<NA>,<NA>,108,97,<NA>,96
3590,T. Turner,1310825728,URI,212,R,95,101,<NA>,<NA>,<NA>,86,<NA>,96
3591,S. Houchens,1194448803,URI,249,L,105,76,<NA>,<NA>,<NA>,103,<NA>,91
798,C. Johnston,1241946624,URI,304,R,77,100,<NA>,80,<NA>,110,<NA>,90

In [28]:
table[table["pitcherId"] == 1307169536]

Empty DataFrame
Columns: [Pitcher, pitcherId, Team, Total, PitcherThrows, Stf+ FA, Stf+ SL, Stf+ CU, Stf+ FC, Stf+ SI, Stf+ CH, Stf+ FS, Stuff+]
Index: []

In [20]:
table[table["Total"] >= 500].sort_values("Stuff+", ascending=False).head(10)

,Pitcher,pitcherId,Team,Total,PitcherThrows,Stf+ FA,Stf+ SL,Stf+ CU,Stf+ FC,Stf+ SI,Stf+ CH,Stf+ FS,Stuff+
2137,H. Dietz,1301090561,ARK,645,L,132,104,145,139,<NA>,<NA>,<NA>,130
1575,D. Volantis,1979617275,TEX,548,L,114,146,131,126,125,101,<NA>,125
2054,C. Carlon,1279321088,ASU,671,L,127,123,107,81,<NA>,93,<NA>,121
1369,L. Peterson,1142994176,FLA,690,R,123,123,110,<NA>,<NA>,108,<NA>,120
4298,M. Edwards,1279382784,USC,707,L,129,116,110,<NA>,<NA>,101,<NA>,119
2576,E. Nachtsheim,1256101932,MCNS,655,R,124,110,104,108,<NA>,100,<NA>,119
655,R. Marohn,1197348608,NCST,602,L,118,112,110,<NA>,115,129,<NA>,119
1332,E. Lund,1985708358,OKST,700,L,119,112,120,<NA>,<NA>,<NA>,<NA>,118
2697,W. Schmidt,1280627385,LSU,662,R,115,121,117,<NA>,<NA>,<NA>,<NA>,118
4247,K. Sweum,1558099259,GONZ,537,L,120,125,<NA>,90,<NA>,79,113,117

In [21]:
table[table["Team"] == "MRMK"].sort_values("Stuff+", ascending=False)

,Pitcher,pitcherId,Team,Total,PitcherThrows,Stf+ FA,Stf+ SL,Stf+ CU,Stf+ FC,Stf+ SI,Stf+ CH,Stf+ FS,Stuff+
3054,A. Holmes,1425232427,MRMK,34,R,112,107,<NA>,<NA>,<NA>,<NA>,<NA>,110
497,S. Franco,1769668118,MRMK,66,L,91,<NA>,101,<NA>,<NA>,111,<NA>,99
3055,C. Barker,1304701440,MRMK,47,R,99,97,<NA>,<NA>,<NA>,<NA>,<NA>,98
496,C. Kiesiner,1402009816,MRMK,99,R,96,97,<NA>,<NA>,<NA>,<NA>,<NA>,96
498,Z. Broderick,1327271424,MRMK,120,L,95,99,<NA>,<NA>,<NA>,97,<NA>,96
1820,N. Hunkele,1342167952,MRMK,73,R,95,86,<NA>,<NA>,<NA>,107,<NA>,96
634,J. Borsari,1213486080,MRMK,48,R,91,92,<NA>,104,<NA>,<NA>,<NA>,95
636,O. Barkal,1384801355,MRMK,108,R,86,95,<NA>,<NA>,<NA>,<NA>,<NA>,93
1821,J. Nichols,1907374041,MRMK,91,R,86,99,<NA>,99,<NA>,<NA>,<NA>,93
3038,B. Loper,1307046400,MRMK,58,R,96,83,<NA>,<NA>,<NA>,102,<NA>,92
499,M. Bradshaw,1223209728,MRMK,88,R,92,90,<NA>,<NA>,<NA>,<NA>,<NA>,91
1819,C. Cassidy,1183063552,MRMK,43,L,86,104,<NA>,<NA>,<NA>,<NA>,<NA>,90
3039,H. Hebert,1846828626,MRMK,59,R,94,84,<NA>,<NA>,<NA>,<NA>,<NA>,90
500,C. Yennaco,1213265409,MRMK,28,R,80,<NA>,95,<NA>,<NA>,<NA>,<NA>,86
637,O. Zadrozny,1260854784,MRMK,52,R,85,81,<NA>,<NA>,<NA>,<NA>,<NA>,84
635,L. Cespedes,1119577088,MRMK,13,R,82,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,82

In [31]:
stuff[stuff["pitcherId"] == 1304701440]

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv,Stuff+
10561,C. Barker,1304701440,MRMK,FA,R,20,-5.723808,18.083514,13.476466,-0.177295,6.136091,-1.525991,6.408032,89.168222,2222.320350,219.664934,0.107134,95
10562,C. Barker,1304701440,MRMK,SL,R,27,-8.636924,-2.136478,-6.163696,-2.312542,5.749747,-1.587969,6.323121,77.669330,2216.939097,57.785514,0.083488,85

In [22]:
table.to_csv("stuff_table.csv")

In [33]:
table[table["Team"] == "CCAR"].sort_values("Stuff+", ascending=False)

,Pitcher,pitcherId,Team,Total,PitcherThrows,Stf+ FA,Stf+ SL,Stf+ CU,Stf+ FC,Stf+ SI,Stf+ CH,Stf+ FS,Stuff+
675,C. Flukey,1238148096,CCAR,59,R,126,<NA>,108,<NA>,<NA>,<NA>,<NA>,117
184,D. Parker,1676824501,CCAR,303,R,117,<NA>,102,<NA>,<NA>,100,<NA>,113
2975,R. Norman,1105483008,CCAR,481,R,104,107,<NA>,<NA>,<NA>,94,<NA>,105
55,J. Appelman,1954026382,CCAR,321,R,92,110,<NA>,<NA>,100,101,<NA>,104
58,S. Doran,1253195181,CCAR,381,R,102,103,107,<NA>,<NA>,<NA>,<NA>,104
78,C. Bosch,1750954648,CCAR,390,L,100,113,<NA>,<NA>,<NA>,108,<NA>,104
54,C. Kane,1162293760,CCAR,219,R,102,98,104,108,<NA>,<NA>,<NA>,103
53,J. Smallets,1317717863,CCAR,216,R,97,106,<NA>,<NA>,101,<NA>,<NA>,102
56,R. Lynch,1185766656,CCAR,92,R,106,99,103,<NA>,<NA>,<NA>,<NA>,102
57,D. Horn,1297495808,CCAR,545,R,98,98,120,86,104,<NA>,<NA>,99
4914,K. Karr,1461773063,CCAR,109,L,95,100,97,<NA>,96,<NA>,<NA>,97
79,C. Richardson,1390499521,CCAR,329,L,100,82,<NA>,<NA>,104,103,<NA>,96
866,L. Jones,1997059014,CCAR,514,R,95,97,<NA>,89,79,<NA>,<NA>,87