In [2]:
import pandas as pd
import numpy as np
import pickle
from lightgbm import LGBMRegressor
MODELS_CACHE = {}

In [3]:
df = pd.read_csv("full_data.csv")

In [4]:
pitchers = list(df["pitcherId"].unique())
pitches = list(df["pitchType"].unique())
pitches.remove("KN")
pitches.remove("ST")
lr = ["L", "R"]

features = ['vertApprAngle', 'inducedVertBreak', 'horzBreak', 'horzApprAngle', 'extension', 'relX', 'relZ', 'releaseVelocity', 'spinRate', 'spinDir']
targets = ["rv"]

test = df[df["year"] == 2025]

In [5]:
def pred_rv(test, features, target, pitch, side):
    if (pitch, side) not in MODELS_CACHE:
        with open(f'models/25_{pitch}_{side}.pkl', 'rb') as f:
            MODELS_CACHE[(pitch, side)] = pickle.load(f)

    model = MODELS_CACHE[(pitch, side)]
    X_test = test[features]
    predictions = model.predict(X_test) 
    
    return pd.Series(predictions, index=test.index)

In [6]:
dfs = []

for pitcher in pitchers: 
    for pitch in pitches: 
        for side in lr: 
            te = test[(test["pitcherId"] == pitcher) & (test["pitchType"] == pitch) & (test["pitcherHand"] == side)] 
            if len(te) >= 10: 
                dfx = {} 
                dfx["Pitcher"] = te["Pitcher"].iloc[0]
                dfx["pitcherId"] = pitcher
                dfx["Team"] = te["pitchingTeam"].iloc[0]
                dfx["PitchType"] = pitch 
                dfx["PitcherThrows"] = side 
                dfx["Count"] = len(te) 
                for feature in features: 
                    dfx[feature] = te[feature].mean() 
                for target in targets: 
                    dfz = pd.DataFrame([dfx], columns=features) 
                    dfx["xrv"] = float(pred_rv(dfz, features, target, pitch, side).iloc[0]) 
                dfs.append(dfx)

In [76]:
stuff = pd.DataFrame(dfs).reset_index(drop=True)

In [8]:
stuff[stuff["Team"] == "URI"].sort_values("xrv")

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv
3001,P. Aikens,1299756340,URI,CU,L,10,-7.364154,4.032466,13.889763,3.975938,4.501587,3.384290,4.513831,72.575203,2590.269408,262.686994,-0.033854
2992,D. Asencio,1241946368,URI,SL,R,113,-7.322495,8.758297,-9.723717,-3.572629,5.581573,-1.844785,5.737151,76.541147,2252.073474,130.289475,0.007156
12981,N. Fletcher,1067176853,URI,CU,L,13,-9.338816,-7.508356,10.670626,2.358651,5.592543,1.441015,4.936968,68.590335,1681.128934,313.890374,0.010195
3012,T. Levesque,1214276096,URI,FA,L,563,-5.332769,21.542431,-6.344312,0.232201,5.851984,0.617154,5.934798,87.273640,2032.010137,162.681280,0.019905
1427,C. Johnston,1241946624,URI,SL,R,103,-9.114918,-5.549883,-17.808652,-3.380795,5.296686,-1.561890,6.053778,75.657785,2566.035418,75.751630,0.028282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,C. Johnston,1241946624,URI,SI,R,12,-6.516243,10.274821,17.636866,0.482325,6.255370,-1.584437,6.012699,85.914307,2265.066130,243.207556,0.130937
1426,C. Johnston,1241946624,URI,FA,R,151,-6.025083,11.654134,12.638104,-0.313798,6.061297,-1.448858,6.116953,84.955957,2209.747747,229.432777,0.137534
3016,Z. Morris,1202393856,URI,FA,R,95,-5.365312,16.630204,12.699680,-0.604363,5.577461,-1.828187,5.757472,87.274775,2304.512224,218.801567,0.139560
12989,B. Hsu,1126083840,URI,CU,R,37,-8.920510,-12.299829,-10.228622,-2.147205,5.260421,-0.999712,5.113542,75.153439,1776.222329,35.284569,0.143876
12979,N. Fletcher,1067176853,URI,FA,L,205,-5.426708,16.309940,-14.155450,0.224355,6.159864,1.498263,5.017077,80.206018,1956.666165,137.320457,0.176398

In [77]:
from scipy import stats

#df['zscore'] = stats.zscore(df['column'])
stuff["Stuff+"] = 100 + (-10 * stuff.groupby("PitchType")["xrv"].transform(stats.zscore))
stuff["Stuff+"] = stuff["Stuff+"].round().astype(int)

In [10]:
stuff.sort_values("Stuff+", ascending=False)

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv,Stuff+
9176,S. Brady,1321144576,LMU,CU,L,140,-10.489160,-18.425456,18.441137,3.252646,5.644665,1.630285,5.728155,72.587248,3122.007927,318.115945,-0.103376,140
14301,J. Mitchell,1262857984,LIP,SL,L,192,-6.808401,9.163681,8.866529,3.927187,5.340532,2.732314,5.283333,77.811683,2528.254230,229.648945,-0.047385,138
3513,B. Cleaver,1318951936,UK,FC,L,54,-7.885573,0.996064,9.471774,4.102667,6.385784,2.824545,5.841386,77.608051,2132.319217,270.531095,-0.185594,136
16808,M. Walsh,1310820352,VCU,SL,L,72,-6.893353,1.748738,16.200957,5.812855,5.698515,4.350179,4.704096,77.148633,2769.594219,269.794363,-0.042602,136
15611,C. Kriebel,1263557376,FGCU,SL,L,138,-7.785183,1.558290,12.393571,3.542551,4.134506,2.573051,5.017280,76.153182,2432.053768,266.758863,-0.040842,136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17139,C. Danz,1436355266,NW,SL,L,18,-3.619750,1.038481,-3.552298,-1.927680,5.816122,-0.714915,2.252179,65.121281,1268.289588,119.145511,0.208826,35
14035,B. Swindle,1208235163,JVST,SL,R,79,-7.339039,-0.907751,1.844646,2.345784,5.307560,1.688762,4.820428,81.799794,2413.357176,275.114296,0.215791,33
11838,A. Anderson,1123493376,NWST,CU,R,11,-5.755975,1.847771,-2.745304,0.331626,5.340767,-0.439775,3.255092,65.928381,1703.250994,170.344554,0.299249,30
12012,J. Lourens,1146595328,JKST,SL,L,43,-8.667477,1.235612,-8.075944,2.241270,4.578433,2.831879,5.398443,71.538700,1728.192238,118.668241,0.231483,26
11347,A. Doganiero,1370596122,PITT,SL,L,14,-5.960132,-6.963013,-4.205966,0.121396,5.517674,0.215786,2.908219,68.405111,1482.586771,114.173914,0.244535,21

In [11]:
stuff.to_csv("stuff.csv")

In [12]:
stuff[stuff["Count"] > 200].sort_values("Stuff+", ascending=False).hea

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv,Stuff+
13244,J. Volini,1320920832,FSU,CU,L,286,-9.847579,-17.443100,11.279419,2.371668,5.446581,1.046487,6.051180,77.516908,2766.827039,329.563768,-0.074178,132
1350,A. Sentlinger,1281698816,VT,FA,L,264,-4.197561,19.787803,-7.529650,0.400823,6.467114,1.316262,5.678269,92.349873,2324.997951,158.536852,-0.039292,130
2846,E. Norby,1335271936,ECU,SL,L,340,-7.443537,-1.123865,15.864906,5.013406,5.533849,3.206451,4.864266,79.439471,3043.516103,278.709807,-0.022379,128
1145,T. Santana,1176403456,CLMB,SL,R,361,-7.085936,8.266907,-14.084440,-3.375774,5.442251,-1.668868,5.625787,78.688127,2248.462193,117.510738,-0.021148,128
755,J. Tallon,1100869376,DUKE,FA,L,377,-4.201008,17.775375,-14.806244,-0.034907,6.546771,1.552238,5.418277,92.070336,2457.105064,138.012929,-0.025045,127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8499,C. Mohan,1821920924,TTU,FA,R,284,-6.058764,16.045741,7.269246,-0.402195,5.401170,-0.901844,6.403218,92.184142,2288.135413,205.235923,0.205108,73
16246,B. Jacobs,1246857984,ASU,FS,L,210,-7.598726,6.327714,-9.456598,-0.315925,5.580122,0.884409,5.339922,82.370789,1284.076454,119.328186,0.405298,72
7857,J. Harris,1216810752,BYU,FA,R,242,-6.243614,11.477442,13.140017,0.803098,5.800649,-0.354034,5.871681,89.478725,1872.030851,230.291135,0.225663,68
1313,C. Cosper,1092635904,MER,SL,L,275,-8.632276,-5.001565,7.106461,2.937681,5.329313,2.345942,5.083604,74.927533,2062.132991,309.696018,0.131754,66
4642,J. Woodward,1262668032,FIU,FA,R,310,-5.893107,16.512370,8.547487,-0.624252,5.501838,-1.098218,6.814068,89.264534,2131.626201,208.087596,0.239573,65

In [57]:
stuff[(stuff["Team"] == "URI") & (stuff["Count"] >= 11)].sort_values("Stuff+", ascending=False).head(60)

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv,Stuff+,weight,weighted_xrv
3012,T. Levesque,1214276096,URI,FA,L,563,-5.332769,21.542431,-6.344312,0.232201,5.851984,0.617154,5.934798,87.273640,2032.010137,162.681280,0.019905,117,0.547133,0.010890
2992,D. Asencio,1241946368,URI,SL,R,113,-7.322495,8.758297,-9.723717,-3.572629,5.581573,-1.844785,5.737151,76.541147,2252.073474,130.289475,0.007156,116,0.289003,0.002068
12987,B. Hsu,1126083840,URI,FA,R,135,-4.351926,20.420219,9.149534,-0.629127,5.988422,-0.900472,5.100162,86.600312,2107.138747,204.903186,0.043232,111,0.553279,0.023919
1419,J. Kopetski,1269533184,URI,FA,L,237,-5.634936,19.619824,-9.754404,1.046684,6.236890,1.589678,5.723711,87.520037,1832.293085,151.950531,0.045096,111,0.628647,0.028349
1430,C. Johnston,1241946624,URI,CH,R,42,-7.651950,6.223617,17.145982,-0.003781,6.239100,-1.470591,5.986494,80.320216,1799.291101,249.361731,0.039314,111,0.117647,0.004625
1416,E. Maloney,1085415168,URI,SI,R,12,-6.797850,13.242778,17.570871,1.702626,5.330377,-0.237006,6.790269,86.536849,2185.940369,235.657018,0.034249,110,0.260870,0.008934
1417,C. Maloney,1336247552,URI,FA,R,38,-5.931722,19.480657,8.535183,-1.895613,6.473471,-1.657670,5.595128,89.023493,2068.572096,205.152050,0.053580,109,0.550725,0.029508
3025,J. Sabbath,1110853376,URI,FA,R,270,-5.060699,18.632913,4.441349,-0.853437,6.262684,-0.979987,5.717739,90.401321,2236.969890,193.766746,0.050333,109,0.542169,0.027289
12981,N. Fletcher,1067176853,URI,CU,L,13,-9.338816,-7.508356,10.670626,2.358651,5.592543,1.441015,4.936968,68.590335,1681.128934,313.890374,0.010195,109,0.050781,0.000518
1427,C. Johnston,1241946624,URI,SL,R,103,-9.114918,-5.549883,-17.808652,-3.380795,5.296686,-1.561890,6.053778,75.657785,2566.035418,75.751630,0.028282,108,0.288515,0.008160
3020,A. Jones,1101042688,URI,FA,R,198,-4.544389,18.626251,5.677784,-0.147415,6.155591,-0.688573,5.615168,89.365853,2150.416928,197.538115,0.056746,108,0.519685,0.029490
3002,P. Aikens,1299756340,URI,SI,L,69,-6.286510,4.367902,-21.110441,2.781313,4.945536,4.409328,4.987055,82.227769,2130.977595,97.591425,0.053793,107,0.155756,0.008379
3024,A. Jones,1101042688,URI,CH,R,16,-7.039962,11.607449,12.395406,-0.088366,5.979784,-1.046171,5.418528,82.758336,1313.052681,230.809101,0.053870,107,0.041995,0.002262
3026,J. Sabbath,1110853376,URI,SL,R,178,-7.877917,1.410960,-10.850299,-2.629685,5.670990,-1.125648,5.597775,78.802531,2295.931538,91.280971,0.032620,106,0.357430,0.011659
2994,J. Cullen,1358089441,URI,FA,R,401,-4.867891,19.101634,13.757547,0.319729,5.721721,-0.883449,5.808931,90.639025,2158.114995,217.515064,0.067054,106,0.579480,0.038856
1424,J. Urena,1241946112,URI,SI,R,155,-6.780621,6.641381,17.173337,-0.462645,5.421682,-1.870837,5.738721,88.623158,1767.191403,252.589649,0.065349,105,0.182139,0.011903
3018,Z. Morris,1202393856,URI,FC,R,45,-7.311161,1.746526,-2.143724,-2.138637,4.910949,-1.970803,5.716860,82.974103,2668.427139,150.314905,0.030969,104,0.154639,0.004789
3021,A. Jones,1101042688,URI,SL,R,109,-7.224915,0.655685,-6.193920,-1.524774,5.578253,-0.664993,5.671558,81.502504,2339.807302,91.636227,0.037098,104,0.286089,0.010613
3023,A. Jones,1101042688,URI,FC,R,33,-7.115622,3.707823,-3.822319,-1.460416,5.631054,-0.994423,5.487494,82.700754,2333.896389,126.362403,0.037282,103,0.086614,0.003229
1428,C. Johnston,1241946624,URI,CU,R,49,-10.686053,-11.778675,-16.192813,-3.836537,5.493852,-1.410818,6.200275,73.535028,2549.109100,52.079147,0.031026,103,0.137255,0.004259
1423,J. Urena,1241946112,URI,SL,R,175,-8.235778,3.490212,-13.699380,-3.645726,5.251813,-1.861216,5.610594,75.926570,2085.022089,104.657755,0.042962,102,0.205640,0.008835
3005,B. Perry,1342168540,URI,SL,R,133,-7.065222,5.483758,-6.628720,-2.740707,5.737835,-1.805994,5.528185,79.559351,2384.532719,129.647602,0.042895,102,0.250943,0.010764
2997,J. Cullen,1358089441,URI,FC,R,64,-6.446816,3.987398,-2.891544,-2.023544,5.400330,-1.264779,5.575516,82.727098,2517.793061,125.761130,0.042660,102,0.092486,0.003945
3015,T. Levesque,1214276096,URI,CH,L,245,-7.443941,13.783017,-11.889298,-0.452912,5.516272,0.851996,5.801802,79.525133,1756.646939,136.191939,0.075837,101,0.238095,0.018056
3013,T. Levesque,1214276096,URI,SL,L,122,-8.696756,-1.088098,8.540570,2.190037,5.131536,0.900402,5.857176,75.099471,1975.001939,277.303333,0.045141,101,0.118562,0.005352
3008,M. Santos,1487988943,URI,FA,R,166,-4.822979,12.484197,11.570616,-0.837537,5.546953,-1.728940,5.225392,90.665863,2321.518959,224.859042,0.087073,101,0.477011,0.041535
12982,N. Fletcher,1067176853,URI,CH,L,13,-6.287658,12.981170,-9.800614,-0.196576,6.069388,1.593520,5.114669,76.277902,1758.295026,149.232970,0.078890,100,0.050781,0.004006
3027,J. Sabbath,1110853376,URI,CU,R,14,-8.736125,-9.259682,-14.505213,-3.190037,5.524936,-0.831898,5.668408,73.931028,2297.156233,53.441936,0.044072,100,0.028112,0.001239
12980,N. Fletcher,1067176853,URI,SL,L,25,-8.297021,-0.357672,6.364190,2.380337,5.840915,1.421224,5.050960,70.952177,1679.230577,278.454444,0.049223,100,0.097656,0.004807
2998,J. Cullen,1358089441,URI,CH,R,103,-7.189153,9.601560,15.965640,0.296119,5.907841,-1.044155,5.767466,84.318584,1654.650828,241.677351,0.079834,100,0.148844,0.011883
3004,B. Perry,1342168540,URI,FA,R,354,-4.926161,16.219876,11.221319,-0.793142,6.401304,-1.676981,5.626731,89.281835,2271.384650,216.326033,0.094483,99,0.667925,0.063107
2995,J. Cullen,1358089441,URI,SL,R,106,-7.320521,0.615510,-5.134480,-1.827609,5.218604,-1.193819,5.736902,80.743938,2551.860121,87.448733,0.051825,99,0.153179,0.007938
3000,P. Aikens,1299756340,URI,SL,L,141,-7.218702,4.511336,15.965188,5.689448,4.415598,3.766431,4.528862,72.867915,2620.320713,254.160930,0.050584,99,0.318284,0.016100
3019,Z. Morris,1202393856,URI,CH,R,19,-6.620216,5.611403,10.626976,-0.101030,5.403802,-2.013694,5.500642,81.955408,2077.077172,247.394281,0.081922,99,0.065292,0.005349
3022,A. Jones,1101042688,URI,CU,R,25,-9.154517,-11.642566,-10.137692,-1.474037,5.652519,-0.819880,5.616626,77.147502,2542.878730,40.082044,0.051436,98,0.065617,0.003375
3006,B. Perry,1342168540,URI,SI,R,19,-5.827071,9.552053,14.835267,-0.972711,6.237314,-1.950745,5.448362,87.281481,2286.061075,235.371026,0.105393,98,0.035849,0.003778
2999,P. Aikens,1299756340,URI,FA,L,184,-6.005985,4.455817,-22.078002,1.802016,4.731832,3.786848,4.790174,82.784048,2135.212475,97.648433,0.097306,98,0.415350,0.040416
2993,D. Asencio,1241946368,URI,CH,R,59,-7.222451,8.781223,17.185941,0.148540,5.748221,-1.880393,5.754688,78.497605,1587.870718,247.371151,0.089471,97,0.150895,0.013501
3017,Z. Morris,1202393856,URI,SL,R,132,-7.147213,0.844445,-2.642090,-2.404453,4.945181,-2.023716,5.552331,82.674050,2632.435614,106.689110,0.055523,97,0.453608,0.025186
3014,T. Levesque,1214276096,URI,CU,L,99,-9.714851,-7.755817,6.199214,1.674145,5.049565,0.790391,5.954411,73.286201,1943.448786,307.468685,0.057052,96,0.096210,0.005489
2996,J. Cullen,1358089441,URI,SI,R,18,-6.735249,10.088290,14.414401,0.371597,5.932114,-0.973428,6.069422,87.413373,1817.823198,240.057580,0.117940,96,0.026012,0.003068
3010,M. Santos,1487988943,URI,SI,R,23,-5.729257,9.009099,17.568758,0.194058,5.642456,-1.802858,5.297573,89.051563,2233.572136,245.172841,0.121055,96,0.066092,0.008001
3009,M. Santos,1487988943,URI,SL,R,147,-7.370019,-0.040561,-9.559395,-3.082710,5.058167,-1.852726,4.983758,78.895561,2390.405047,83.670721,0.056958,96,0.422414,0.024060
12988,B. Hsu,1126083840,URI,SL,R,54,-7.854880,-2.394806,-10.357801,-2.517234,5.329195,-1.157436,5.126334,77.319991,2066.208579,72.540686,0.060722,95,0.221311,0.013438
1418,C. Maloney,1336247552,URI,SL,R,31,-8.953419,-2.704296,-7.798871,-2.949303,5.567099,-1.841032,5.730505,79.608956,2569.130576,65.317962,0.060098,95,0.449275,0.027001
1429,C. Johnston,1241946624,URI,SI,R,12,-6.516243,10.274821,17.636866,0.482325,6.255370,-1.584437,6.012699,85.914307,2265.066130,243.207556,0.130937,94,0.033613,0.004401
12978,B. Levin,1210140672,URI,FA,R,55,-6.042888,8.712866,1.560029,-1.645763,5.357257,-1.668475,4.888288,82.373482,2202.041403,188.994447,0.115509,94,1.000000,0.115509
1425,J. Urena,1241946112,URI,CH,R,204,-7.252053,6.008690,14.575369,-0.268617,5.504151,-1.908733,5.595041,83.732473,1543.641416,250.565541,0.098909,94,0.239718,0.023710
12990,B. Hsu,1126083840,URI,CH,R,18,-6.645646,8.301231,14.865127,-0.070759,5.925876,-1.227468,4.908483,79.113072,1521.564978,243.241460,0.099081,94,0.073770,0.007309
17704,R. Thompson,1708929273,URI,FA,R,38,-6.729479,15.917336,7.033791,-0.869268,5.986257,-1.538996,6.405318,79.253170,2020.619385,205.354102,0.117312,94,1.000000,0.117312
2991,D. Asencio,1241946368,URI,FA,R,219,-5.632099,17.844284,13.297646,-0.688271,5.832173,-1.766101,5.883304,86.912253,2172.006198,218.972991,0.122229,93,0.560102,0.068461
1422,J. Urena,1241946112,URI,FA,R,317,-6.333468,7.630200,16.652542,-0.347233,5.504919,-1.894268,5.488913,88.006389,1761.000021,248.389212,0.118967,93,0.372503,0.044315
1421,J. Kopetski,1269533184,URI,CH,L,60,-7.546463,10.539010,-15.744013,0.382814,6.404832,2.046794,5.498172,78.071689,1702.409431,119.777270,0.101970,93,0.159151,0.016229
1415,E. Maloney,1085415168,URI,FA,R,34,-6.183733,18.859163,12.072477,0.738122,5.157306,0.005845,6.943972,87.401385,2205.607641,214.512387,0.130495,91,0.739130,0.096453
3011,M. Santos,1487988943,URI,CH,R,12,-6.304243,11.906168,14.523207,0.708217,6.083884,-1.832766,4.936105,80.297298,1540.101069,236.275819,0.110605,91,0.034483,0.003814
3007,B. Perry,1342168540,URI,CH,R,24,-6.781553,3.863749,12.029251,-0.670867,5.997911,-2.171695,5.113303,82.885223,1900.447036,254.244553,0.112490,91,0.045283,0.005094
3016,Z. Morris,1202393856,URI,FA,R,95,-5.365312,16.630204,12.699680,-0.604363,5.577461,-1.828187,5.757472,87.274775,2304.512224,218.801567,0.139560,89,0.326460,0.045561
1426,C. Johnston,1241946624,URI,FA,R,151,-6.025083,11.654134,12.638104,-0.313798,6.061297,-1.448858,6.116953,84.955957,2209.747747,229.432777,0.137534,89,0.422969,0.058173
3028,J. Sabbath,1110853376,URI,CH,R,36,-6.917030,5.981536,12.462454,-0.294691,6.285391,-1.356746,5.445818,84.104857,1616.569786,246.230320,0.120622,88,0.072289,0.008720
3003,P. Aikens,1299756340,URI,CH,L,39,-6.867651,4.607475,-18.644649,1.711089,4.947080,3.497522,4.716797,79.225295,2053.408762,98.597218,0.124307,87,0.088036,0.010943

In [79]:
stuff[(stuff["Count"] > 50) & (stuff["PitchType"] == "FA")].sort_values("Stuff+", ascending=False).head(10)

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv,Stuff+
11657,J. Mayers,1307169536,LSU,FA,R,149,-5.464745,22.633968,7.231550,-1.149329,6.200066,-1.655203,7.111829,96.951614,2553.557814,198.416404,-0.037991,130
1350,A. Sentlinger,1281698816,VT,FA,L,264,-4.197561,19.787803,-7.529650,0.400823,6.467114,1.316262,5.678269,92.349873,2324.997951,158.536852,-0.039292,130
755,J. Tallon,1100869376,DUKE,FA,L,377,-4.201008,17.775375,-14.806244,-0.034907,6.546771,1.552238,5.418277,92.070336,2457.105064,138.012929,-0.025045,127
467,K. Emmons,1299809537,TOWS,FA,R,153,-4.717626,22.787661,9.717267,-0.746498,5.894912,-1.288321,6.211975,91.917438,2306.112495,204.569674,-0.024219,127
538,M. Gaither,1138681856,ULL,FA,L,102,-4.302027,18.683955,-18.165671,1.244674,4.877600,2.619864,5.378726,90.606004,2535.843004,133.648338,-0.023919,127
10325,S. Garcia,1602557566,ORE,FA,L,291,-4.749893,22.562727,-7.634308,0.833956,6.075337,1.368665,6.039528,91.938543,2306.112760,160.382131,-0.025897,127
13041,W. Sanford,1518897568,ORE,FA,R,457,-4.313728,22.106422,8.496320,-1.000238,6.583986,-1.572086,5.609768,91.443800,2459.161361,201.948129,-0.022509,126
9277,R. Ojeda,1142126848,UCI,FA,L,507,-4.448310,19.587006,-7.030891,1.182023,7.079689,1.425053,5.524121,90.889894,2235.526087,159.345437,-0.020634,126
11059,S. Fitzpatrick,1082403072,ASU,FA,L,126,-4.146151,13.229334,-16.085928,2.183028,6.369231,3.253769,4.593835,89.274559,2157.777802,126.971067,-0.019390,126
16581,T. Shaw,1885286845,GRAM,FA,L,56,-5.333288,21.479325,-3.094230,1.127771,6.869783,1.406667,6.231262,90.415476,1988.409607,171.216467,-0.018610,126

In [55]:
stuff[stuff["pitcherId"] == 1110853376]

,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv,Stuff+,weight,weighted_xrv
3025,J. Sabbath,1110853376,URI,FA,R,270,-5.060699,18.632913,4.441349,-0.853437,6.262684,-0.979987,5.717739,90.401321,2236.969890,193.766746,0.050333,109,0.542169,0.027289
3026,J. Sabbath,1110853376,URI,SL,R,178,-7.877917,1.410960,-10.850299,-2.629685,5.670990,-1.125648,5.597775,78.802531,2295.931538,91.280971,0.032620,106,0.357430,0.011659
3027,J. Sabbath,1110853376,URI,CU,R,14,-8.736125,-9.259682,-14.505213,-3.190037,5.524936,-0.831898,5.668408,73.931028,2297.156233,53.441936,0.044072,100,0.028112,0.001239
3028,J. Sabbath,1110853376,URI,CH,R,36,-6.917030,5.981536,12.462454,-0.294691,6.285391,-1.356746,5.445818,84.104857,1616.569786,246.230320,0.120622,88,0.072289,0.008720

In [ ]:
rows = []
ids = list(stuff["pitcherId"].unique())

for i in ids:
    x = stuff[stuff["pitcherId"] == i]
    dx = {}
    dx["Pitcher"] = x["Pitcher"].iloc[0]
    dx["pitcherId"] = i
    dx["Team"] = x["Team"].iloc[0]
    dx["PitcherThrows"] = x["PitcherThrows"].iloc[0]
    for pt in list(stuff["PitchType"].unique()):
        if pt in list(x["PitchType"].unique()):
            dx["Stf+ " + pt] = x[x["PitchType"] == pt]["Stuff+"].iloc[0].astype("int64")
        else:
            dx["Stf+ " + pt] = np.nan
    rows.append(dx)

In [64]:
table = pd.DataFrame(rows).reset_index(drop=True)
stf_cols = [col for col in table.columns if col.startswith("Stf+")]
table[stf_cols] = table[stf_cols].astype("Int64")

In [51]:
total = stuff.groupby("pitcherId")["Count"].transform("sum")
stuff["weight"] = stuff["Count"] / total
stuff["weighted_xrv"] = stuff["xrv"] * stuff["weight"]

overall = stuff.groupby("pitcherId")["weighted_xrv"].sum().reset_index()
overall.columns = ["pitcherId", "overall_xrv"]

overall["Stuff+"] = (100 + (-10 * stats.zscore(overall["overall_xrv"]))).round().astype(int)

table = table.merge(overall[["pitcherId", "Stuff+"]], on="pitcherId", how="left")

In [74]:
table[table["Team"] == "UMBC"]

,Pitcher,pitcherId,Team,PitcherThrows,Stf+ FA,Stf+ SL,Stf+ CU,Stf+ FC,Stf+ SI,Stf+ CH,Stf+ FS
340,M. Cunningham,1279329792,UMBC,R,90,94,91,<NA>,<NA>,<NA>,<NA>
341,N. Remy,1310848000,UMBC,R,112,94,<NA>,116,<NA>,<NA>,100
343,S. Murphy,1138622464,UMBC,R,93,112,<NA>,<NA>,<NA>,<NA>,<NA>
344,Z. Kelly,1299084032,UMBC,R,94,99,105,<NA>,<NA>,<NA>,<NA>
345,E. Sargent,1162067200,UMBC,L,96,78,<NA>,97,42,102,<NA>
346,S. Bell,1235469056,UMBC,R,94,97,<NA>,103,<NA>,<NA>,100
438,L. Wiley,1223210240,UMBC,L,102,97,94,<NA>,<NA>,100,<NA>
1076,B. Fox,1866778115,UMBC,L,101,74,106,101,<NA>,<NA>,<NA>
1077,C. Ho,1162473728,UMBC,R,101,100,105,93,<NA>,<NA>,<NA>
1078,A. Denham,1181602304,UMBC,R,101,94,<NA>,<NA>,<NA>,<NA>,109
1119,E. Tolis,1322649088,UMBC,R,102,86,83,<NA>,<NA>,113,<NA>
1120,A. Gonzalez,1342169249,UMBC,R,104,109,<NA>,<NA>,110,<NA>,<NA>
1271,E. Selmer,1162475008,UMBC,R,105,<NA>,<NA>,<NA>,<NA>,112,<NA>
3186,S. Droz,1676399105,UMBC,R,102,86,<NA>,<NA>,<NA>,103,<NA>
3187,E. Ianni,1523440032,UMBC,R,92,98,<NA>,<NA>,<NA>,106,<NA>
3188,Z. Robinson,1948501770,UMBC,R,91,88,<NA>,99,99,97,<NA>
5223,G. Teschendorf,1394606419,UMBC,R,<NA>,<NA>,<NA>,<NA>,102,<NA>,<NA>

In [84]:
table[table["pitcherId"] == 1307169536]

,Pitcher,pitcherId,Team,PitcherThrows,Stf+ FA,Stf+ SL,Stf+ CU,Stf+ FC,Stf+ SI,Stf+ CH,Stf+ FS
3235,J. Mayers,1307169536,LSU,R,130,109,<NA>,<NA>,<NA>,<NA>,<NA>

In [83]:
pd.set_option('display.max_columns', None)
df[df["pitcherId"] == 1307169536].sort_values("relZ", ascending=False).head(10)

,Unnamed: 0,year,pitchingTeamId,pitchingTeam,conference,hittingTeamId,hittingTeam,gameId,gameDate,inning,balls,strikes,outs,pitcherId,Pitcher,pitcherHand,pitchType,plateLocX,plateLocZ,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,pitchResult,atbatResult,relX,relZ,releaseVelocity,spinRate,spinDir,rv
4012772,4012772,2024,730284032,NICH,D1 Southland Conference,3374,LT,4539508,2024-04-24 13:00:00,5,0,0,1,1307169536,J. Mayers,R,FA,-0.72145,0.33376,-8.431952,26.25206,2.33335,1.084220,5.15745,B,HR,0.10509,7.55541,93.05228,2461.661087,185.307216,0.13
4012770,4012770,2024,730284032,NICH,D1 Southland Conference,3374,LT,4539508,2024-04-24 13:00:00,5,1,2,0,1307169536,J. Mayers,R,FA,-0.09942,5.18122,-3.255412,24.86328,1.50984,0.376756,5.28923,B,K,0.12863,7.53764,95.49019,2463.796783,183.622289,0.13
4012775,4012775,2024,730284032,NICH,D1 Southland Conference,3374,LT,4539508,2024-04-24 13:00:00,5,1,2,1,1307169536,J. Mayers,R,FA,1.00845,4.72130,-3.802185,24.94316,0.39890,-0.914734,5.38323,B,HR,0.11772,7.53049,93.90292,2412.455954,180.954297,0.13
4012767,4012767,2024,730284032,NICH,D1 Southland Conference,3374,LT,4539508,2024-04-24 13:00:00,5,0,0,0,1307169536,J. Mayers,R,FA,0.76164,4.36465,-4.197598,25.78860,-2.35744,-1.051372,5.45427,B,K,-0.02638,7.51500,92.68573,2396.989014,174.546833,0.13
762127,762127,2025,5323,LSU,D1 Southeastern Conference,5380,UNO,163441134,2025-03-18 18:33:00,6,1,1,0,1307169536,J. Mayers,R,FA,-0.56202,4.48085,-4.125358,24.60127,7.49237,0.275663,5.94998,B,IP_OUT,-0.93010,7.49928,94.15018,2384.831528,197.761689,0.13
4561384,4561384,2024,730284032,NICH,D1 Southland Conference,3031,UCI,5336410,2024-05-31 13:00:00,1,1,0,0,1307169536,J. Mayers,R,FA,-1.39446,3.15185,-5.627129,23.44915,-1.32768,1.125710,5.40048,B,BB,-0.22890,7.49547,93.33306,2479.111004,176.603206,0.13
4012778,4012778,2024,730284032,NICH,D1 Southland Conference,3374,LT,4539508,2024-04-24 13:00:00,5,3,2,1,1307169536,J. Mayers,R,FA,0.17250,2.04332,-6.713619,24.24143,-1.37480,-0.040971,5.37119,IP,HR,0.24855,7.48704,93.71944,2423.720894,176.596544,1.76
4012773,4012773,2024,730284032,NICH,D1 Southland Conference,3374,LT,4539508,2024-04-24 13:00:00,5,1,0,1,1307169536,J. Mayers,R,FA,-0.15373,2.87798,-5.851156,24.74671,0.25106,0.164786,5.40325,SL,HR,-0.02023,7.48050,92.51050,2392.275371,180.609061,-0.15
4561386,4561386,2024,730284032,NICH,D1 Southland Conference,3031,UCI,5336410,2024-05-31 13:00:00,1,3,0,0,1307169536,J. Mayers,R,FA,-0.62713,2.18385,-6.736835,22.37100,-2.56169,0.188869,5.53479,SL,BB,-0.23722,7.47939,93.39470,2382.495573,173.131011,-0.15
4012768,4012768,2024,730284032,NICH,D1 Southland Conference,3374,LT,4539508,2024-04-24 13:00:00,5,1,0,0,1307169536,J. Mayers,R,FA,0.99919,2.31010,-6.331536,25.93588,2.16559,-1.047344,5.15205,SL,K,-0.16712,7.47459,92.54644,2470.213977,184.988639,-0.15