In [13]:
import pandas as pd

df1 = pd.read_csv("stuff.csv")
df2 = pd.read_csv("../data/Fall25Scrim(updated).csv")

df1["spinDir"].describe()

count    17766.000000
mean       175.123706
std         72.618773
min         16.561063
25%        113.735712
50%        193.522479
75%        234.512614
max        348.347440
Name: spinDir, dtype: float64

In [14]:
df2["SpinAxis"].describe()

count    3258.000000
mean      184.364320
std        68.779644
min         2.479290
25%       135.555262
50%       204.365991
75%       230.886502
max       359.937595
Name: SpinAxis, dtype: float64

In [12]:
df1[(df1["pitcherId"] == 1487988943	) & (df1["PitchType"] == "SL")]

,Unnamed: 0,Pitcher,pitcherId,Team,PitchType,PitcherThrows,Count,vertApprAngle,inducedVertBreak,horzBreak,horzApprAngle,extension,relX,relZ,releaseVelocity,spinRate,spinDir,xrv,Stuff+
3009,3009,M. Santos,1487988943,URI,SL,R,147,-7.370019,-0.040561,-9.559395,-3.08271,5.058167,-1.852726,4.983758,78.895561,2390.405047,83.670721,0.056958,96

In [17]:
df2[(df2["Pitcher"] == "Santos, Manny") & (df2["TaggedPitchType"] == "Slider")][["VertApprAngle", "HorzApprAngle"]]

      VertApprAngle  HorzApprAngle
213       -6.838249      -2.321980
217       -8.116022      -7.045198
218       -6.900294      -3.290414
219       -8.279005      -3.949453
220       -6.917826      -4.705274
...             ...            ...
2703      -6.794573      -6.412887
2704      -7.459089      -3.739526
2705      -6.803550      -2.086352
2708      -7.980653      -6.297270
2709      -7.387442      -5.187746

[82 rows x 2 columns]